name: Run Tests

on:
  push:
    paths:
      - ".github/workflows/**"
      - "tests/**"
      - "*.sh"

env:
  LAB_REP: zhengzangw/C--_Compiler
  LAB_NAME: Lab
  LAB_PATH: Lab/Lab1/Code

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -yq bison flex

      - name: Checkout Tests
        uses: actions/checkout@v2

      - name: Checkout Lab Codes
        uses: actions/checkout@v2
        with:
          repository: ${{ LAB_REPO }}
          token: ${{ secrets.GITHUB_PAT }}
          path: ${{ LAB_NAME }}

      - name: Build Lab Binary
        run: |
          cd $LAB_PATH
          make parser

      - name: Run Test
        run: |
          chmod +x run_quiet.sh
          ./run_quiet.sh $LAB_PATH/parser | tee result.txt


      - name: Upload Result
        uses: actions/upload-artifact@v1
        with:
          name: result
          path: result.txt
