name: Run Tests

on: push

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -yq bison flex
          flex --version
          bison --version

      - name: Checkout Tests
        uses: actions/checkout@v2

      - name: Checkout Lab Codes
        uses: actions/checkout@v2
        with:
          repository: zhengzangw/C--_Compiler
          token: ${{ secrets.GITHUB_PAT }}
          path: Lab

      - name: Build Lab Binary
        run: |
          cd Lab
          make parser

      - name: Run Test
        run: |
          chmod +x autotest.sh
          ./autotest.sh Lab/parser | tee result.txt

      - name: Upload Result
        uses: actions/upload-artifact@v1
        with:
          name: result
          path: result.txt
